#include "../include/cfrtil64.h"

#if RETRO
namespace retro
{
    void retro ( void ) ;
} ;
#endif

#if 0 //SL5
namespace Sl5
{
    void sl5 ( void ) ;
    void isl5 ( void ) ;
} ;
#endif

CPrimitive CPrimitives [] = {
    { "(", 0, 0, ( block ) LO_ReadEvalPrint_AfterAFirstLParen, IMMEDIATE | KEYWORD, LEFT_PAREN, 0, "Lisp", "Root" },
    { "_(", 0, 0, ( block ) LC_Read, IMMEDIATE | KEYWORD, 0, 0, "Lisp", "Root" },
    { "eval", 0, 0, ( block ) LC_Eval, IMMEDIATE | KEYWORD, 0, 0, "Lisp", "Root" },
    { "print", 0, 0, ( block ) LC_PrintWithValue, 0, 0, 0, "Lisp", "Root" },
    { ")", 0, 0, CfrTil_NoOp, IMMEDIATE | KEYWORD, NO_OP_WORD, 0, "Lisp", "Root" },
    { "_Printf", 0, 0, ( block ) _Printf, 0, 0, LISP_C_RTL_ARGS | T_LISP_SPECIAL | LISP_VOID_RETURN, "Lisp", "Root" },
    { "define", 0, 0, ( block ) LO_Define, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "compile", 0, 0, ( block ) LO_CompileDefine, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "_lambda", 0, 0, ( block ) LO_Lambda, 0, 0, T_LAMBDA | T_LISP_SPECIAL, "Lisp", "Root" },
    { "lambda", 0, 0, ( block ) LO_Lambda, IMMEDIATE, 0, T_LAMBDA | T_LISP_SPECIAL, "Lisp", "Root" },
    { "begin", 0, 0, ( block ) LO_Begin, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "set", 0, 0, ( block ) LO_Set, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "let", 0, 0, ( block ) LO_Let, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "if*", 0, 0, ( block ) LO_Cond, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "macro", 0, 0, ( block ) _LO_Macro, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" }, // nb. too many clashes with other 'if's
    { ".if", 0, 0, ( block ) LO_Cond, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "cond", 0, 0, ( block ) LO_Cond, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "car", 0, 0, ( block ) LO_Car, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "cdr", 0, 0, ( block ) LO_Cdr, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "quote", 0, 0, ( block ) LO_Quote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "eval", 0, 0, ( block ) _LC_Eval, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "list", 0, 0, ( block ) LO_List, 0, 0, LIST_FUNCTION | T_LISP_SPECIAL, "Lisp", "Root" },
    { "'", 0, 0, ( block ) LO_Quote, KEYWORD, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "@", 0, 0, ( block ) LO_Splice, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "quasiquote", 0, 0, ( block ) LO_QuasiQuote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "`", 0, 0, ( block ) LO_QuasiQuote, KEYWORD, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "unquote", 0, 0, ( block ) LO_UnQuote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { ",", 0, 0, ( block ) LO_UnQuote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "unquoteSplicing", 0, 0, ( block ) LO_UnQuoteSplicing, 0, 0, T_LISP_UNQUOTE_SPLICING | T_LISP_READ_MACRO, "Lisp", "Root" },
    { ",@", 0, 0, ( block ) LO_UnQuoteSplicing, 0, 0, T_LISP_UNQUOTE_SPLICING | T_LISP_READ_MACRO, "Lisp", "Root" },
    { "::", 0, 0, ( block ) _LO_CfrTil, 0, 0, T_LISP_CFRTIL | T_LISP_SPECIAL | T_LISP_IMMEDIATE, "Lisp", "Root" },
    //{ ":", 0, 0, ( block ) _LO_Colon, 0, 0, T_LISP_COLON | T_LISP_IMMEDIATE | T_LISP_SPECIAL, "Lisp", "Root" },
    { "lcReset", 0, 0, ( block ) LC_Reset, 0, 0, 0, "Lisp", "Root" },
    //{ ":", 0, 0, ( block ) _LO_Colon, 0, 0, T_LISP_COLON | T_LISP_IMMEDIATE | T_LISP_SPECIAL, "Lisp", "Root" },

    { "'", 0, 0, CfrTil_SingleQuote, IMMEDIATE | KEYWORD, 0, 0, "Forth", "Root" },

    { "_Printf", 0, 0, ( block ) _Printf, LISP_C_RTL_ARGS | LISP_VOID_RETURN, 0, 0, "C", "Root" },
    { "printf", 0, 0, ( block ) _Printf, C_PREFIX_RTL_ARGS, 0, 0, "C", "Root" },
    { "sprintf", 0, 0, ( block ) sprintf, C_PREFIX_RTL_ARGS, 0, 0, "C", "Root" },
    //{ ")", 0, 0, CfrTil_NoOp, IMMEDIATE, 0, 0, "C", "Root" },
    { "()", 0, 0, CfrTil_NoOp, IMMEDIATE, 0, 0, "C", "Root" },
    //{ "(", 0, 0, CfrTil_LocalsAndStackVariablesBegin, IMMEDIATE | KEYWORD, 0, 0, "C", "Root" },
    //{ "(", 0, 0, Interpret_DoParenthesizedRValue, IMMEDIATE | KEYWORD, 0, 0, "C", "Root" },
    { "(", 0, 0, CfrTil_C_LeftParen, IMMEDIATE | KEYWORD, LEFT_PAREN, 0, "C", "Root" },
    { "(|", 0, 0, CfrTil_LocalVariablesBegin, IMMEDIATE, 0, 0, "C", "Root" },
    //{ "|-", 0, 0, CfrTil_NoOp, IMMEDIATE, 0, 0, "C", "Root" },
    { "if{", 0, 0, CfrTil_If, IMMEDIATE, 0, 0, "C", "Root" },
    { "}else{", 0, 0, CfrTil_Else, IMMEDIATE, 0, 0, "C", "Root" },
    { "}fi", 0, 0, CfrTil_EndIf, IMMEDIATE, 0, 0, "C", "Root" },
    { "case", 0, 0, CfrTil_Case, IMMEDIATE, 0, 0, "C", "Root" },
    { "switch", 0, 0, CfrTil_Switch, IMMEDIATE, 0, 0, "C", "Root" },
    { ">?", 0, 0, CfrTil_EndIf, IMMEDIATE, 0, 0, "C", "Root" },
    // { ">;", 0, 0, CfrTil_EndIf, IMMEDIATE, 0, 0, "C", "Root" },
    { ">:<", 0, 0, CfrTil_Else, IMMEDIATE, 0, 0, "C", "Root" },
    { "?<", 0, 0, CfrTil_If, IMMEDIATE, 0, 0, "C", "Root" },
    { "++", 5, INC, CfrTil_PlusPlus, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_PLUS_PLUS_MINUS_MINUS, 0, 0, "C", "Root" },
    { "--", 5, DEC, CfrTil_MinusMinus, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_PLUS_PLUS_MINUS_MINUS, 0, 0, "C", "Root" },
    //{ "lReturnTOS", 0, 0, CfrTil_Locals_ReturnTOS, IMMEDIATE, 0, 0, "C", "Root" },
    //{ "lReturnR8", 0, 0, CfrTil_Locals_ReturnR8, IMMEDIATE, 0, 0, "C", "Root" },
    //{ "cReturnR8", 0, 0, CfrTil_CReturnR8, IMMEDIATE, 0, 0, "C", "Root" },
    //{ "cstackPush", 0, 0, Compile_DspPop_RspPush, IMMEDIATE, 0, 0, "C", "Root" },
    { "cfib", 0, 0, CFib, 0, 0, 0, "C", "Root" },
    { "cfactorial", 0, 0, CFactorial, 0, 0, 0, "C", "Root" },
    { "cfactorial2", 0, 0, CFactorial2, 0, 0, 0, "C", "Root" },
    { "cfactorial3", 0, 0, CFactorial3, 0, 0, 0, "C", "Root" },
    { "cfib_O3", 0, 0, CFib_O3, 0, 0, 0, "C", "Root" },
    { "cfib2_O3", 0, 0, CFib2_O3, 0, 0, 0, "C", "Root" },
    { "cfactorial_O3", 0, 0, CFactorial_O3, 0, 0, 0, "C", "Root" },
    { "cfactorial2_O3", 0, 0, CFactorial2_O3, 0, 0, 0, "C", "Root" },
    { "cfactorial3_O3", 0, 0, CFactorial3_O3, 0, 0, 0, "C", "Root" },
    //{ "'", 0, 0, CfrTil_Tick, IMMEDIATE, 0, 0, "C", "Root" },
    { "c_rtl", 0, 0, CfrTil_C_Prefix, IMMEDIATE, 0, 0, "C", "Root" },
    { "c_prefix", 0, 0, CfrTil_C_Prefix, IMMEDIATE, 0, 0, "C", "Root" },
    { "c_return", 0, 0, CfrTil_C_Return, IMMEDIATE, 0, 0, "C", "Root" },
    { "void_return", 0, 0, CfrTil_Void_Return, IMMEDIATE, 0, 0, "C", "Root" },
    { "rax_return", 0, 0, CfrTil_RAX_Return, IMMEDIATE, 0, 0, "C", "Root" },

    { "{", 0, 0, CfrTil_Begin_C_Block, IMMEDIATE | KEYWORD, 0, 0, "C_Syntax", "C" },
    { "}", 0, 0, CfrTil_End_C_Block, IMMEDIATE | KEYWORD, 0, 0, "C_Syntax", "C" },
    { "s{", 0, 0, CfrTil_DbgSourceCode_Begin_C_Block, IMMEDIATE, 0, 0, "C_Syntax", "C" },
    { "}s", 0, 0, CfrTil_DbgSourceCode_End_C_Block, IMMEDIATE, 0, 0, "C_Syntax", "C" },
    { ";", 0, 0, CfrTil_C_Semi, IMMEDIATE | KEYWORD, SYNTACTIC, 0, "C_Syntax", "C" },
    { ",", 0, 0, CfrTil_NoOp, IMMEDIATE | KEYWORD, NO_OP_WORD, 0, "C_Syntax", "C" },
    { "!", 0, TEST, CfrTil_LogicalNot, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_LOGIC | PREFIX, 0, 0, "C_Syntax", "C" },
    { "c_class", 0, 0, ( block ) CfrTil_C_Class_New, 0, 0, 0, "C_Syntax", "C" },
    { "type", 0, 0, ( block ) CfrTil_Type_New, 0, 0, 0, "C_Syntax", "C" },
    { "typedef", 0, 0, CfrTil_Typedef, 0, 0, 0, "C_Syntax", "C" },
    { "&", 0, 0, CfrTil_AddressOf, IMMEDIATE, NO_CODING, ADDRESS_OF_OP, "C_Syntax", "C" }, // avoid name clash with '&&' and '&' 
    //{ "=", 0, 0, (block) CfrTil_C_Infix_Equal, IMMEDIATE | CATEGORY_EQUAL | KEYWORD, 0, 0, "C_Syntax", "C" }, //"Infix", "Compiler" },

    { "}", 0, 0, CfrTil_TypedefStructEnd, IMMEDIATE | KEYWORD, 0, 0, "C_Typedef", "C_Syntax" },
    { "{", 0, 0, CfrTil_TypedefStructBegin, IMMEDIATE | KEYWORD, 0, 0, "C_Typedef", "C_Syntax" },

    //{ ")", 0, 0, CfrTil_EndBlock, IMMEDIATE, 0, 0, "C_Combinators", "C" },
    //{ "(", 0, 0, CfrTil_BeginBlock, IMMEDIATE, 0, 0, "C_Combinators", "Combinators" },
    { "if", 0, 0, CfrTil_If_C_Combinator, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "C_Combinators", "C" },
    { "while", 0, 0, CfrTil_While_C_Combinator, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "C_Combinators", "C" },
    { "do", 0, 0, CfrTil_DoWhile_C_Combinator, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "C_Combinators", "C" },
    { "for", 0, 0, CfrTil_For_C_Combinator, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "C_Combinators", "C" },
    { "loop", 0, 0, CfrTil_Loop_C_Combinator, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "C_Combinators", "C" },

    { ":", 0, 0, CfrTil_Colon, IMMEDIATE | KEYWORD, 0, 0, "Infix", "Compiler" },
    //{ "(", 0, 0, Interpret_DoParenthesizedRValue, IMMEDIATE | KEYWORD, LEFT_PAREN, 0, "Infix", "Compiler" },
    { "=", 0, MOV, ( block ) CfrTil_C_Infix_Equal, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL | KEYWORD, 0, 0, "Infix", "C" }, //"Infix", "Compiler" },
    //{ ")", 0, 0, CfrTil_EndBlock, IMMEDIATE | KEYWORD, RIGHT_PAREN, 0, "Infix", "Compiler" },

    { "(", 0, 0, CfrTil_LocalsAndStackVariablesBegin, IMMEDIATE | KEYWORD, LEFT_PAREN, 0, "Locals", "Root" },
    { "(|", 0, 0, CfrTil_LocalVariablesBegin, IMMEDIATE, 0, 0, "Locals", "Root" },

    //{ "linrec", 0, 0, CfrTil_Combinator_LinRec, COMBINATOR|IMMEDIATE, 0, 0, "Combinators", "Root" },
    //{ "ifte", 0, 0, CfrTil_TrueFalseCombinator3, COMBINATOR|IMMEDIATE|RT_STACK_OP, 0, 0, "Combinators", "Root" },
    //{ "ifElse", 0, 0, CfrTil_TrueFalseCombinator3, COMBINATOR|IMMEDIATE|RT_STACK_OP, 0, 0, "Combinators", "Root" },
    { "tf2", 0, 0, CfrTil_TrueFalseCombinator2, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "tf3", 0, 0, CfrTil_TrueFalseCombinator3, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if1", 0, 0, CfrTil_If1Combinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if", 0, 0, CfrTil_If2Combinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if2", 0, 0, CfrTil_If2Combinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if3", 0, 0, CfrTil_TrueFalseCombinator3, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    //{ "cond", 0, 0, CfrTil_If2Combinator, COMBINATOR|IMMEDIATE|RT_STACK_OP, 0, 0, "Combinators", "Root" },
    { "while", 0, 0, ( block ) CfrTil_WhileCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "doWhile", 0, 0, ( block ) CfrTil_DoWhileCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "doWhileDo", 0, 0, CfrTil_DoWhileDoCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "call", 0, 0, CfrTil_BlockRun, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "run", 0, 0, CfrTil_BlockRun, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "_call", 0, 0, CfrTil_BlockRun, COMBINATOR, 0, 0, "Combinators", "Root" },
    { "_run", 0, 0, CfrTil_BlockRun, COMBINATOR, 0, 0, "Combinators", "Root" },
    { "_", 0, 0, CfrTil_DropBlock, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "loop", 0, 0, CfrTil_LoopCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    //{ "nloop", 0, 0, CfrTil_NLoopCombinator, COMBINATOR, 0, 0, "Combinators", "Root" },
    { "for", 0, 0, CfrTil_ForCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },

    { "in", 0, 0, CfrTil_PrintInNamespace, 0, 0, 0, "Namespace", "Root" },
    { "using", 0, 0, CfrTil_Using, 0, 0, 0, "Namespace", "Root" },
    { "usingFirst", 0, 0, CfrTil_Namespace_UsingFirst, 0, 0, 0, "Namespace", "Root" },
    { "usingLast", 0, 0, CfrTil_Namespace_UsingLast, 0, 0, 0, "Namespace", "Root" },
    { "notUsing", 0, 0, CfrTil_Namespace_NotUsing, 0, 0, 0, "Namespace", "Root" },
    { "namespaces", 0, 0, CfrTil_Namespaces, 0, 0, 0, "Namespace", "Root" },
    { "namespaceTree", 0, 0, CfrTil_Namespaces_PrettyPrintTree, 0, 0, 0, "Namespace", "Root" },
    { "namespaceTreeWithWords", 0, 0, CfrTil_Namespaces_PrettyPrintTreeWithWords, 0, 0, 0, "Namespace", "Root" },
    { "words", 0, 0, CfrTil_Words, 0, 0, 0, "Namespace", "Root" },
    { "allWords", 0, 0, CfrTil_AllWords, 0, 0, 0, "Namespace", "Root" },
    { "_namespaceWords", 0, 0, _CfrTil_NamespaceWords, 0, 0, 0, "Namespace", "Root" },
    { "namespaceWords", 0, 0, CfrTil_NamespaceWords, 0, 0, 0, "Namespace", "Root" },
    { "namespace", 0, 0, CfrTil_Namespace_New, 0, 0, 0, "Namespace", "Root" },
    //{ "sealed", 0, 0, CfrTil_NamespaceSealed, 0, 0, 0, "Namespace", "Root" },
    { "_find", 0, 0, CfrTil_Postfix_Find, 0, 0, 0, "Namespace", "Root" },
    //{ "find", 0, 0, CfrTil_Postfix_Find, IMMEDIATE, 0, 0, "Namespace", "Root" },

    { "};", 0, 0, CfrTil_ClassStructureEnd, 0, 0, 0, "Class", "Root" },
    { "+:{", 0, 0, CfrTil_CloneStructureBegin, 0, 0, 0, "Class", "Root" },
    { ":{", 0, 0, CfrTil_ClassStructureBegin, 0, 0, 0, "Class", "Root" },
    { "class", 0, 0, CfrTil_Class_New, 0, 0, 0, "Class", "Root" },
    { "new", 0, 0, ( block ) CfrTil_Class_Value_New, 0, 0, 0, "Class", "Root" },
    { "clone", 0, 0, CfrTil_Class_Clone, 0, 0, 0, "Class", "Root" },
    { "]", 0, 0, CfrTil_ArrayEnd, ( IMMEDIATE | OBJECT_OPERATOR ), 0, 0, "Class", "Root" },
    { "[", 0, 0, CfrTil_ArrayBegin, ( IMMEDIATE | OBJECT_OPERATOR ), 0, 0, "Class", "Root" },
    { ".", 0, 0, CfrTil_Dot, ( IMMEDIATE | OBJECT_OPERATOR ), NO_CODING, 0, "Class", "Root" },

    { "pWidth", 0, 0, BigNum_Set_PrintfWidth, 0, 0, 0, "BigNum", "Class" },
    { "pPrecision", 0, 0, BigNum_Set_PrintfPrecision, 0, 0, 0, "BigNum", "Class" },
    //{ "bPrecision", 0, 0, BigNum_SetDefaultBitPrecision, 0, 0, 0, "BigNum", "Class" },
    { "bnState", 0, 0, BigNum_StateShow, 0, 0, 0, "BigNum", "Class" },

    //{ "get_p_pWidth", 0, 0, BigNum_GetPrintfWidth_Pointer, 0, 0, 0, "BigNum", "Class" },
    //{ "get_p_pPrecision", 0, 0, BigNum_GetPrintfPrecision_Pointer, 0, 0, 0, "BigNum", "Class" },
    { "+", 0, 0, BigNum_Add, 0, 0, 0, "BigNum", "Class" },
    { "-", 0, 0, BigNum_Subtract, 0, 0, 0, "BigNum", "Class" },
    { "+=", 0, 0, BigNum_PlusEqual, 0, 0, 0, "BigNum", "Class" },
    { "++", 0, 0, BigNum_PlusPlus, 0, 0, 0, "BigNum", "Class" },
    { "-=", 0, 0, BigNum_MinusEqual, 0, 0, 0, "BigNum", "Class" },
    { "--", 0, 0, BigNum_MinusMinus, 0, 0, 0, "BigNum", "Class" },
    { "*", 0, 0, BigNum_Multiply, 0, 0, 0, "BigNum", "Class" },
    { "*=", 0, 0, BigNum_MultiplyEqual, 0, 0, 0, "BigNum", "Class" },
    { "^", 0, 0, BigNum_Power, 0, 0, 0, "BigNum", "Class" },
    { "/", 0, 0, BigNum_Divide, 0, 0, 0, "BigNum", "Class" },
    { "/=", 0, 0, BigNum_DivideEqual, 0, 0, 0, "BigNum", "Class" },
    { "==", 0, 0, ( block ) BigNum_Equal, 0, 0, 0, "BigNum", "Class" },
    { "<=", 0, 0, ( block ) BigNum_LessThanOrEqual, 0, 0, 0, "BigNum", "Class" },
    { "<", 0, 0, ( block ) BigNum_LessThan, 0, 0, 0, "BigNum", "Class" },
    { "sqrt", 0, 0, ( block ) BigNum_SquareRoot, 0, 0, 0, "BigNum", "Class" },
    { "pow", 0, 0, ( block ) BigNum_Power, 0, 0, 0, "BigNum", "Class" },
    { "^", 0, 0, ( block ) BigNum_Power, 0, 0, 0, "BigNum", "Class" },
    { "**", 0, 0, ( block ) BigNum_Power, 0, 0, 0, "BigNum", "Class" },
    { ">=", 0, 0, ( block ) BigNum_GreaterThanOrEqual, 0, 0, 0, "BigNum", "Class" },
    { ">", 0, 0, ( block ) BigNum_GreaterThan, 0, 0, 0, "BigNum", "Class" },
    { "==", 0, 0, ( block ) BigNum_LogicalEquals, 0, 0, 0, "BigNum", "Class" },
    { "!=", 0, 0, ( block ) BigNum_LogicalDoesNotEqual, 0, 0, 0, "BigNum", "Class" },
    { "_eprint", 0, 0, BigNum_EPrint, 0, 0, 0, "BigNum", "Class" },
    { "_fprint", 0, 0, BigNum_FPrint, 0, 0, 0, "BigNum", "Class" },

    { "||", 1, OR, CfrTil_LogicalOr, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    //{ "or", 0, 0, CfrTil_LogicalOr, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "or", 1, OR, CfrTil_LogicalOr, IMMEDIATE | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "xor", 1, XOR, CfrTil_LogicalXor, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "^^", 1, XOR, CfrTil_LogicalXor, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "!", 0, TEST, CfrTil_LogicalNot, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_LOGIC, 0, 0, "Logic", "Root" },
    { "not", 0, TEST, CfrTil_LogicalNot, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_LOGIC, 0, 0, "Logic", "Root" },
    //{ "and", 0, OP_LOGICAL_AND, CfrTil_LogicalAnd, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "and", 0, TEST, CfrTil_LogicalAnd, IMMEDIATE | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    //{ "&&", 1, AND, CfrTil_LogicalAnd, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "&&", 1, CMP, CfrTil_LogicalAnd, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "<", 1, CMP, CfrTil_LessThan, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { ">", 1, CMP, CfrTil_GreaterThan, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "==", 1, CMP, CfrTil_Equals, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "equal", 1, CMP, CfrTil_Equals, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC, 0, 0, "Logic", "Root" },
    { "!=", 1, CMP, CfrTil_DoesNotEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "<=", 1, CMP, CfrTil_LessThanOrEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { ">=", 1, CMP, CfrTil_GreaterThanOrEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },

    { "+", 1, ADD, CfrTil_Plus, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "-", 1, SUB, CfrTil_Minus, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "+=", 1, ADD, CfrTil_PlusEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_OPEQUAL | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "-=", 1, SUB, CfrTil_MinusEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_OPEQUAL | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "*", 3, MUL, CfrTil_Multiply, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "**", 0, 0, CfrTil_Power, CATEGORY_OP_ORDERED | CATEGORY_OP | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "pow", 0, 0, CfrTil_Power, CATEGORY_OP_ORDERED | CATEGORY_OP | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "pow_03", 0, 0, CfrTil_Power_03, CATEGORY_OP_ORDERED | CATEGORY_OP | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "^", 0, 0, CfrTil_Power, CATEGORY_OP_ORDERED | CATEGORY_OP | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "/", 3, DIV, CfrTil_Divide, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_DIVIDE | CATEGORY_OP_ORDERED | INFIXABLE | KEYWORD, OP_RAX_PLUS_1ARG, 0, "Int", "Root" },
    { "modulo", 3, MODULO, CfrTil_Mod, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_DIVIDE | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "%", 3, DIV, CfrTil_Mod, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_DIVIDE | CATEGORY_OP_ORDERED | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "*=", 3, MUL, CfrTil_MultiplyEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_OPEQUAL | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "/=", 3, DIV, CfrTil_DivideEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_OPEQUAL | CATEGORY_OP_ORDERED | INFIXABLE | KEYWORD, OP_RAX_PLUS_1ARG, 0, "Int", "Root" },
    //{ "%=", 0, 0, CfrTil_ModEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    //{ "++", 0, 0, CfrTil_PlusPlus, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG, 0, 0, "Int", "Root" },
    //{ "--", 0, 0, CfrTil_MinusMinusRValue, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG, 0, 0, "Int", "Root" },
    { "intPrint", 0, 0, CfrTil_PrintInt, 0, 0, 0, "Int", "Root" },
    { "hexIntPrint", 0, 0, CfrTil_HexPrintInt, 0, 0, 0, "Int", "Root" },

    { "<<", 2, SHL, CfrTil_ShiftLeft, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | BIT_SHIFT | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { ">>", 2, SHR, CfrTil_ShiftRight, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | BIT_SHIFT | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { "&", 1, AND, CfrTil_BitWise_AND, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { "|", 1, OR, CfrTil_BitWise_OR, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { "^", 1, XOR, CfrTil_BitWise_XOR, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_UNORDERED, 0, 0, "Bits", "Logic" },
    { "~", 3, NOT, CfrTil_BitWise_NOT, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG, 0, 0, "Bits", "Logic" },
    { "neg", 3, NEG, CfrTil_BitWise_NEG, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG, 0, 0, "Bits", "Logic" },
    { "<<=", 2, SHL, CfrTil_ShiftLeft_Equal, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | BIT_SHIFT | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { ">>=", 2, SHR, CfrTil_ShiftRight_Equal, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | BIT_SHIFT | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { "&=", 1, AND, CfrTil_BitWise_AndEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },
    { "|=", 1, OR, CfrTil_BitWise_OrEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | INFIXABLE | KEYWORD, 0, 0, "Bits", "Logic" },

    { "_fi", 0, 0, CfrTil_EndIf, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "_else_", 0, 0, CfrTil_Else, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "if_", 0, 0, CfrTil_If, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "Jmp", 0, 0, CfrTil_JMP, IMMEDIATE, 0, 0, "Asm", "Root" },
    //{ "cmp", 0, 0, CfrTil_CMP, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED, 0, 0, "Asm", "Root" },
    //{ "test", 0, 0, CfrTil_TEST, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED, 0, 0, "Asm", "Root" },
    { "jmpHere", 0, 0, CfrTil_JmpToHere, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "Jcc", 0, 0, CfrTil_Compile_Jcc, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "jcc", 0, 0, CfrTil_Jcc_Label, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "label", 0, 0, CfrTil_Label, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "goto", 0, 0, CfrTil_Goto, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "label:", 0, 0, CfrTil_Label_Prefix, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "goto:", 0, 0, CfrTil_Goto_Prefix, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "jmp", 0, 0, CfrTil_Goto, IMMEDIATE, 0, 0, "Asm", "Root" },

    { "Strlen", 0, 0, CfrTil_Strlen, 0, 0, 0, "String", "Root" },
    { "strcmp", 0, 0, CfrTil_Strcmp, 0, 0, 0, "String", "Root" },
    { "strcat", 0, 0, CfrTil_StrCat, 0, 0, 0, "String", "Root" },
    { "strcpy", 0, 0, CfrTil_StrCpy, 0, 0, 0, "String", "Root" },
    { "stricmp", 0, 0, CfrTil_Stricmp, 0, 0, 0, "String", "Root" },

    { "\"", 0, 0, CfrTil_DoubleQuoteMacro, IMMEDIATE | KEYWORD | CATEGORY_OP_STACK, 0, T_LISP_TERMINATING_MACRO, "Lexer", "Root" },
    { "%", 0, 0, MultipleEscape, IMMEDIATE, 0, 0, "Lexer", "Root" },

    { "printString", 0, 0, CfrTil_PrintString, 0, 0, 0, "Io", "Root" },
    { "emit", 0, 0, CfrTil_Emit, 0, 0, 0, "Io", "Root" },
    { "key", 0, 0, CfrTil_Key, 0, 0, 0, "Io", "Root" },
    { "kbhit", 0, 0, CfrTil_Kbhit, 0, 0, 0, "Io", "Root" },
    { "newline", 0, 0, CfrTil_NewLine, 0, 0, 0, "Io", "Root" },
    { "cr", 0, 0, CfrTil_CarriageReturn, 0, 0, 0, "Io", "Root" },
    { "tab", 0, 0, CfrTil_TAB, 0, 0, 0, "Io", "Root" },
    { "space", 0, 0, CfrTil_SPACE, 0, 0, 0, "Io", "Root" },
    { "logAppend", 0, 0, CfrTil_LogAppend, 0, 0, 0, "Io", "Root" },
    { "logWrite", 0, 0, CfrTil_LogWrite, 0, 0, 0, "Io", "Root" },
    { "logOn", 0, 0, CfrTil_LogOn, 0, 0, 0, "Io", "Root" },
    { "logOff", 0, 0, CfrTil_LogOff, 0, 0, 0, "Io", "Root" },
    //{ "nprintf", 0, 0, CfrTil_printf, PREFIX, 0, 0, "Io", "Root" },

    { "dump", 0, 0, CfrTil_Dump, 0, 0, 0, "Debug", "Root" },
    { "dis", 0, 0, CfrTil_Disassemble, 0, 0, 0, "Debug", "Root" },
    { "wordDisassemble", 0, 0, CfrTil_Word_Disassemble, 0, 0, 0, "Debug", "Root" },
    { "sourceAdd", 0, 0, CfrTil_Source_AddToHistory, 0, 0, 0, "Debug", "Root" },
    { "source", 0, 0, CfrTil_Source_AddToHistory, 0, 0, 0, "Debug", "Root" },
    { "sourceDontAdd", 0, 0, CfrTil_Source_DontAddToHistory, 0, 0, 0, "Debug", "Root" },
    { "stack", 0, 0, CfrTil_PrintDataStack, 0, 0, 0, "Debug", "Root" },
    { "rstack", 0, 0, CfrTil_PrintReturnStack, 0, 0, 0, "Debug", "Root" },
    //{ "rspRegstack", 0, 0, CfrTil_PrintRspRegStack, 0, 0, 0, "Debug", "Root" },
    { "nrstack", 0, 0, CfrTil_PrintNReturnStack, 0, 0, 0, "Debug", "Root" },
    { "dstack", 0, 0, CfrTil_PrintNDataStack_8, 0, 0, 0, "Debug", "Root" },
    { "ndstack", 0, 0, CfrTil_PrintNDataStack, 0, 0, 0, "Debug", "Root" },
    { "s{", 0, 0, CfrTil_DbgSourceCodeBeginBlock, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "}s", 0, 0, CfrTil_DbgSourceCodeEndBlock, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "s:", 0, 0, CfrTil_SourceCodeCompileOn, IMMEDIATE, 0, 0, "Debug", "Root" },
    { ";s", 0, 0, CfrTil_SourceCodeCompileOff, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "dbgSourceCodeOn", 0, 0, _CfrTil_DbgSourceCodeCompileOn, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "dbgSourceCodeOff", 0, 0, _CfrTil_DbgSourceCodeCompileOff, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "scOff", 0, 0, CfrTil_DbgSourceCodeOff, 0, 0, 0, "Debug", "Root" },
    { "scOn", 0, 0, CfrTil_DbgSourceCodeOn, 0, 0, 0, "Debug", "Root" },
    { "_dbgOn", 0, 0, CfrTil_DebugOn, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    { "_dbgOff", 0, 0, CfrTil_DebugOff, INTERPRET_DBG, 0, 0, "Debug", "Root" },
    { ";d", 0, 0, CfrTil_DebugOff, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    //{ "_dbg", 0, 0, CfrTil_Debug, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    //{ "_<dbg>", 0, 0, CfrTil_DebugRuntimeBreakpoint, DEBUG_WORD | INTERPRET_DBG, RT_STEPPING_DEBUG, 0, "Debug", "Root" },
    { "xtDbg", 0, 0, CfrTil_Debug_AtAddress, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    //{ "regs", 0, 0, CfrTil_CpuState_Show, DEBUG_WORD, 0, 0, "Debug", "Root" },
    { "_info", 0, 0, _CfrTil_DebugInfo, DEBUG_WORD, 0, 0, "Debug", "Root" },
    { "info", 0, 0, CfrTil_DebugInfo, DEBUG_WORD, 0, 0, "Debug", "Root" },
    { "localsShow", 0, 0, CfrTil_LocalsShow, DEBUG_WORD, 0, 0, "Debug", "Root" },
    //{ "dbgVerbosity", 0, 0, CfrTil_Debugger_Verbosity, DEBUG_WORD, 0, 0, "Debug", "Root" },
    { "stop", 0, 0, CfrTil_DebugStop, DEBUG_WORD, 0, 0, "Debug", "Root" },
    //{ "dfnba", 0, 0, Debug_Find_Bug, 0, 0, 0, "Debug", "Root" },
    //{ "_pause", 0, 0, OpenVmTil_Pause, DEBUG_WORD, 0, 0, "Debug", "Root" },
    //{ "cpuStateTest", 0, 0, CpuState_test, 0, 0, 0, "Debug", "Root" },

    { "include", 0, 0, CfrTil_IncludeFile, 0, 0, 0, "System", "Root" },
    { "reset", 0, 0, CfrTil_WarmInit, 0, 0, 0, "System", "Root" },
    { "stackInit", 0, 0, CfrTil_DataStack_Init, 0, 0, 0, "System", "Root" },
    { "stackDepth", 0, 0, CfrTil_DataStack_Size, 0, 0, 0, "System", "Root" },
    { "filename", 0, 0, CfrTil_Filename, 0, 0, 0, "System", "Root" },
    //{ "try", 0, 0, CfrTil_Try, 0, 0, 0, "System", "Root" },
    //{ "catch", 0, 0, CfrTil_Catch, 0, 0, 0, "System", "Root" },
    { "throw", 0, 0, CfrTil_Throw, 0, 0, 0, "System", "Root" },
    { "lineNumber", 0, 0, CfrTil_LineNumber, 0, 0, 0, "System", "Root" },
    { "charNumber", 0, 0, CfrTil_LineCharacterNumber, 0, 0, 0, "System", "Root" },
    { "version", 0, 0, CfrTil_Version, 0, 0, 0, "System", "Root" },
    { "decimal", 0, 0, CfrTil_Decimal, 0, 0, 0, "System", "Root" },
    { "hex", 0, 0, CfrTil_Hex, 0, 0, 0, "System", "Root" },
    { "binary", 0, 0, CfrTil_Binary, 0, 0, 0, "System", "Root" },
    { "state", 0, 0, CfrTil_SystemState_Print, 0, 0, 0, "System", "Root" },
    { "variables", 0, 0, CfrTil_Variables, 0, 0, 0, "System", "Root" },
    //{ "verboseOn", 0, 0, CfrTil_VerboseOn, 0, 0, 0, "System", "Root" },
    { "echoOff", 0, 0, CfrTil_EchoOff, 0, 0, 0, "System", "Root" },
    { "echoOn", 0, 0, CfrTil_EchoOn, 0, 0, 0, "System", "Root" },
    { "echoOff", 0, 0, CfrTil_EchoOff, 0, 0, 0, "System", "Root" },
    { "echo", 0, 0, CfrTil_Echo, IMMEDIATE, 0, 0, "System", "Root" },
    //{ "optimize", 0, 0, _CfrTil_SystemState_Print, 0, 0, 0, "System", "Root" },
    { "timeInit", 0, 0, CfrTil_InitTime, 0, 0, 0, "System", "Root" },
    { "timerInit", 0, 0, CfrTil_TimerInit, 0, 0, 0, "System", "Root" },
    { "time", 0, 0, CfrTil_Time, 0, 0, 0, "System", "Root" },
    //{ "shellFork", 0, 0, CfrTil_ShellForkKonsole, 0, 0, 0, "System", "Root" },
    { "shell", 0, 0, CfrTil_ShellEscape, 0, 0, 0, "System", "Root" },
    { "system0", 0, 0, CfrTil_system0, 0, 0, 0, "System", "Root" },
    { "system1", 0, 0, CfrTil_system1, 0, 0, 0, "System", "Root" },
    { "system2", 0, 0, CfrTil_system2, 0, 0, 0, "System", "Root" },
    { "system3", 0, 0, CfrTil_system3, 0, 0, 0, "System", "Root" },
    //{ "dlsym", 0, 0, _CfrTil_Dlsym, 0, 0, 0, "System", "Root" },
    { "returnFromFile", 0, 0, CfrTil_ReturnFromFile, 0, 0, 0, "System", "Root" },
    { "allocateMem", 0, 0, CfrTil_AllocateNew, 0, 0, 0, "System", "Root" },
    //{ "freeObjMem", 0, 0, OVT_MemListFree_Objects, 0, 0, 0, "System", "Root" },
    { "freeSessionMem", 0, 0, OVT_MemListFree_Session, 0, 0, 0, "System", "Root" },
    { "mem", 0, 0, OVT_ShowMemoryAllocated, 0, 0, 0, "System", "Root" },
    { "resetAll", 0, 0, CfrTil_ResetAll, 0, 0, 0, "System", "Root" },
    { "bye", 0, 0, OVT_Exit, 0, 0, 0, "System", "Root" },
    { "abort", 0, 0, CfrTil_Abort, 0, 0, 0, "System", "Root" },
    { "quit", 0, 0, CfrTil_Quit, 0, 0, 0, "System", "Root" },
    { "systemBreak", 0, 0, CfrTil_SystemBreak, 0, 0, 0, "System", "Root" },
    { "exit", 0, 0, OVT_Exit, 0, 0, 0, "System", "Root" },
    { "restart", 0, 0, CfrTil_Restart, 0, 0, 0, "System", "Root" },
    { "restartInit", 0, 0, CfrTil_RestartInit, 0, 0, 0, "System", "Root" },
    { "ri", 0, 0, CfrTil_RestartInit, 0, 0, 0, "System", "Root" },
    { "fullRestart", 0, 0, CfrTil_FullRestart, 0, 0, 0, "System", "Root" },
    { "fr", 0, 0, CfrTil_FullRestart, 0, 0, 0, "System", "Root" },
    { "warmInit", 0, 0, CfrTil_WarmInit, 0, 0, 0, "System", "Root" },
    { "ok", 0, 0, OVT_Ok, 0, 0, 0, "System", "Root" },
    { "console", 0, 0, Console, 0, 0, 0, "System", "Root" },
    { "cpuStateShow", 0, 0, CfrTil_CpuState_CheckShow, 0, 0, 0, "System", "Root" },
    { "location", 0, 0, CfrTil_Location, 0, 0, 0, "System", "Root" },
    { "pause", 0, 0, OpenVmTil_Pause, 0, 0, 0, "System", "Root" },
    { "_pause", 0, 0, OpenVmTil_Pause, 0, 0, 0, "System", "Root" },
    { "registers", 0, 0, _Debugger_CpuState_Show, 0, 0, 0, "System", "Root" },
    { "if", 0, 0, CfrTil_If, IMMEDIATE, 0, 0, "Shell", "Root" },
    { "else", 0, 0, CfrTil_Else, IMMEDIATE, 0, 0, "Shell", "Root" },
    { "endif", 0, 0, CfrTil_EndIf, IMMEDIATE, 0, 0, "Shell", "Root" },
    { "_sh", 0, 0, ShellEscape_Postfix, 0, 0, 0, "Shell", "Root" },
    { "$", 0, 0, shell, 0, 0, 0, "Shell", "Root" },
    //{ "sh", 0, 0, shell, 0, 0, 0, "Shell", "Root" },

    //{ "window", 0, 0, CfrTil_Window, 0, 0, 0, "System", "Root" },
    //{ "testAnd", 0, 0, TestAnd, 0, 0, 0, "System", "Root" },
    //{ "call_a7", 0, 0, call_a7, 0, 0, 0, "System", "Root" },

    { "fopen", 0, 0, File_Open, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fclose", 0, 0, File_Close, 0, 0, 0, "File", "System" },
    { "fwrite", 0, 0, File_Write, 0, 0, 0, "File", "System" },
    { "fread", 0, 0, File_Read, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fseek", 0, 0, File_Seek, 0, 0, 0, "File", "System" },
    { "ftell", 0, 0, File_Tell, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fsize", 0, 0, File_Size, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fexists", 0, 0, File_Exists, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "freadToString", 0, 0, File_ReadToString, 0, 0, 0, "File", "System" },

    { "setDefaultRGB", 0, 0, CfrTil_SetDefaultRGB, 0, 0, 0, "Colors", "System" },
    { "setAlertRGB", 0, 0, CfrTil_SetAlertRGB, 0, 0, 0, "Colors", "System" },
    { "setDebugRGB", 0, 0, CfrTil_SetDebugRGB, 0, 0, 0, "Colors", "System" },
    { "setUserRGB", 0, 0, CfrTil_SetDebugRGB, 0, 0, 0, "Colors", "System" },
    { "setNoticeRGB", 0, 0, CfrTil_SetNoticeRGB, 0, 0, 0, "Colors", "System" },
    { "setUserColors", 0, 0, CfrTil_SetUserColors, 0, 0, 0, "Colors", "System" },
    { "setDefaultColors", 0, 0, CfrTil_SetDefaultColors, 0, 0, 0, "Colors", "System" },
    { "setAlertColors", 0, 0, CfrTil_SetAlertColors, 0, 0, 0, "Colors", "System" },
    { "setDebugColors", 0, 0, CfrTil_SetDebugColors, 0, 0, 0, "Colors", "System" },
    { "setNoticeColors", 0, 0, CfrTil_SetNoticeColors, 0, 0, 0, "Colors", "System" },
    { "debugColors", 0, 0, Ovt_DebugColors, 0, 0, 0, "Colors", "System" },
    { "noticeColors", 0, 0, Ovt_NoticeColors, 0, 0, 0, "Colors", "System" },
    { "defaultColors", 0, 0, Ovt_DefaultColors, 0, 0, 0, "Colors", "System" },
    { "userColors", 0, 0, Ovt_UserColors, 0, 0, 0, "Colors", "System" },
    { "alertColors", 0, 0, Ovt_AlertColors, 0, 0, 0, "Colors", "System" },

    //{ "contextNewRun", 0, 0, CfrTil_Contex_New_RunWord, 0, 0, 0, "Context", "Root" },
    //{ "contextInit", 0, 0, CfrTil_ContextInit, 0, 0, 0, "Context", "Root" },

    { "autoVar", 0, 0, Ovt_AutoVar, 0, 0, 0, "OpenVmTil", "Root" },
    { "autoVarOn", 0, 0, Ovt_AutoVarOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "autoVarOff", 0, 0, Ovt_AutoVarOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "optimize", 0, 0, Ovt_Optimize, 0, 0, 0, "OpenVmTil", "Root" },
    { "inlining", 0, 0, Ovt_Inlining, 0, 0, 0, "OpenVmTil", "Root" },
    { "optimizeOn", 0, 0, CfrTil_OptimizeOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "optimizeOff", 0, 0, CfrTil_OptimizeOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "stringMacrosOn", 0, 0, CfrTil_StringMacrosOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "stringMacrosOff", 0, 0, CfrTil_StringMacrosOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "inlineOff", 0, 0, CfrTil_InlineOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "inlineOn", 0, 0, CfrTil_InlineOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "debugOff", 0, 0, CfrTil_DebugOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "debugOn", 0, 0, CfrTil_DebugOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "verbosity", 0, 0, OpenVmTil_Verbosity, STACK_VARIABLE, 0, 0, "OpenVmTil", "Root" },
    { "codeSize", 0, 0, OpenVmTil_CodeSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "objectsSize", 0, 0, OpenVmTil_ObjectsSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "compilerTempObjectsSize", 0, 0, OpenVmTil_CompilerTempObjectsSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "sessionObjectsSize", 0, 0, OpenVmTil_SessionObjectsSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "dictionarySize", 0, 0, OpenVmTil_DictionarySize, 0, 0, 0, "OpenVmTil", "Root" },
    { "dataStackSize", 0, 0, OpenVmTil_DataStackSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "historySize", 0, 0, OpenVmTil_HistorySize, 0, 0, 0, "OpenVmTil", "Root" },
    { "addToHistory", 0, 0, OpenVmTil_AddStringToHistory, 0, 0, 0, "OpenVmTil", "Root" },
    { "historyReset", 0, 0, HistorySpace_Reset, 0, 0, 0, "OpenVmTil", "Root" },
    { "addToHistoryOn", 0, 0, OpenVmTil_AddStringToHistoryOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "addToHistoryOff", 0, 0, OpenVmTil_AddStringToHistoryOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "showAllocated", 0, 0, OVT_Mem_ShowAllocated, 0, 0, 0, "OpenVmTil", "Root" },

    { "_dup", 0, 0, CfrTil_Dup, CATEGORY_DUP | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "dup", 0, 0, CfrTil_Dup, IMMEDIATE | CATEGORY_DUP | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "ndup", 0, 0, CfrTil_NDup, CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "drop", 0, 0, CfrTil_Drop, IMMEDIATE | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "dropN", 0, 0, CfrTil_DropN, IMMEDIATE | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "_ndrop", 0, 0, CfrTil_DropN, CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "pick", 0, 0, CfrTil_Pick, IMMEDIATE | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "_swap", 0, 0, CfrTil_Swap, 0, 0, 0, "Stack", "Root" },
    { "dsp", 0, 0, CfrTil_Dsp, CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "stackCheck", 0, 0, DataStack_Check, 0, 0, 0, "Stack", "Root" },

    { "lisp", 0, 0, ( block ) LO_Repl, 0, 0, 0, "List", "Root" },
    { "_(", 0, 0, ( block ) LC_Read, IMMEDIATE | KEYWORD, 0, 0, "List", "Root" },
    { "eval", 0, 0, ( block ) LC_Eval, IMMEDIATE | KEYWORD, 0, 0, "List", "Root" },
    { "printList", 0, 0, ( block ) LC_PrintWithValue, 0, 0, 0, "List", "Root" },
    { "dupList", 0, 0, ( block ) LC_DupList, 0, 0, 0, "List", "Root" },
    { "lcReset", 0, 0, ( block ) LC_RestoreStack, 0, 0, 0, "List", "Root" },

    //{ "compileMode_get", 0, 0, CfrTil_CompileMode, 0, 0, 0, "Interpreter", "Root" },
    { "compileMode", 0, 0, CfrTil_CompileMode, 0, 0, 0, "Interpreter", "Root" },
    { "compileModeOn", 0, 0, CfrTil_RightBracket, 0, 0, 0, "Interpreter", "Root" },
    { "compileModeOff", 0, 0, CfrTil_LeftBracket, 0, 0, 0, "Interpreter", "Root" },
    { "//", 0, 0, CfrTil_CommentToEndOfLine, IMMEDIATE | KEYWORD, 0, W_COMMENT, "Interpreter", "Root" },
    { "#!", 0, 0, CfrTil_CommentToEndOfLine, IMMEDIATE, 0, W_COMMENT, "Interpreter", "Root" },
    { "*/", 0, 0, CfrTil_NoOp, IMMEDIATE, 0, W_COMMENT, "Interpreter", "Root" },
    { "/*", 0, 0, CfrTil_ParenthesisComment, IMMEDIATE, 0, W_COMMENT, "Interpreter", "Root" },
    { "eval", 0, 0, CfrTil_Interpreter_EvalWord, 0, 0, 0, "Interpreter", "Root" },
    //{ "literalInterpret", 0, 0, CfrTil_InterpretALiteralToken, 0, 0, 0, "Interpreter", "Root" },
    { "doWord", 0, 0, CfrTil_DoWord, 0, 0, 0, "Interpreter", "Root" },
    { "tokenToWord", 0, 0, CfrTil_TokenToWord, 0, 0, 0, "Interpreter", "Root" },
    { "interpretString", 0, 0, CfrTil_InterpretString, 0, 0, 0, "Interpreter", "Root" },
    { "interpretNextToken", 0, 0, CfrTil_InterpretNextToken, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterRun", 0, 0, CfrTil_InterpreterRun, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterInit", 0, 0, CfrTil_Interpreter_Init, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterStop", 0, 0, CfrTil_InterpreterStop, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterIsDone", 0, 0, CfrTil_Interpreter_IsDone, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterDone", 0, 0, CfrTil_Interpreter_Done, 0, 0, 0, "Interpreter", "Root" },
    { "interpret", 0, 0, CfrTil_InterpreterRun, 0, 0, 0, "Interpreter", "Root" },
    { "interpretFile", 0, 0, CfrTil_Interpret, 0, 0, 0, "Interpreter", "Root" },
    { "l:", 0, 0, CfrTil_Interpret_ReadToList, 0, 0, 0, "Interpreter", "Root" },
    { "_lx_", 0, 0, CfrTil_Interpret_List, 0, 0, 0, "Interpreter", "Root" },

    { "#", 0, 0, CfrTil_PreProcessor, IMMEDIATE, 0, W_PREPROCESSOR, "Interpreter", "Root" },


    { "!", 0, 0, CfrTil_CommentToEndOfLine, 0, 0, W_PREPROCESSOR, "PreProcessor", "Root" }, // in init.cft ; needed for script files starting with #! cfrtil -s
    { "endif", 0, 0, CfrTil_Endif_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "else", 0, 0, CfrTil_Else_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "if", 0, 0, CfrTil_If_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "elif", 0, 0, CfrTil_Elif_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "define", 0, 0, CfrTil_Define, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },

    { "sm:", 0, 0, CfrTil_StringMacro, 0, 0, 0, "Macro", "Root" },
    { "alias", 0, 0, CfrTil_Alias, 0, 0, 0, "Macro", "Root" },
    { "tm:", 0, 0, CfrTil_TextMacro, 0, 0, 0, "Macro", "Root" },

    { "name", 0, 0, Word_Name, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "create", 0, 0, CfrTil_Word_Create, 0, 0, 0, "Word", "Root" },
    { "wNamespace", 0, 0, Word_Namespace, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "compileTimeLocation", 0, 0, CompileTime_Location, IMMEDIATE, DO_DOES, 0, "Word", "Root" },
    { "locationPush", 0, 0, Location_PushNew, 0, 0, 0, "Word", "Root" },
    { "locationPrint", 0, 0, Location_Printf, 0, 0, 0, "Word", "Root" },
    { "wordEval", 0, 0, CfrTil_Word_Eval, 0, 0, 0, "Word", "Root" },
    { "wordRun", 0, 0, CfrTil_Word_Run, 0, 0, 0, "Word", "Root" },
    { "definition", 0, 0, Word_Definition, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "value", 0, 0, Word_Value, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "xt", 0, 0, Word_Xt_LValue, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    //{ "xt@", 0, 0, Word_Definition, IMMEDIATE, 0, 0, "Word", "Root" },
    //{ "xt!", 0, 0, Word_DefinitionStore, 0, 0, 0, "Word", "Root" },
    { "xt=", 0, 0, Word_DefinitionEqual, 0, 0, 0, "Word", "Root" },
    { "wordFinish", 0, 0, Word_Finish, 0, 0, 0, "Word", "Root" },
    { "wordAdd", 0, 0, Word_Add, 0, 0, 0, "Word", "Root" },
    { "codeStart", 0, 0, Word_CodeStart, 0, 0, 0, "Word", "Root" },
    { "codeSize", 0, 0, Word_CodeSize, 0, 0, 0, "Word", "Root" },
    { "addrToWord", 0, 0, AddressToWord, 0, 0, 0, "Word", "Root" },

    // Dynamic Object - DObject
    { "dobject", 0, 0, CfrTil_SetPropertiesAsDObject, 0, 0, 0, "DObject", "Root" },
    { "clone", 0, 0, CfrTil_DObject_Clone, 0, 0, 0, "DObject", "Root" },
    { "new", 0, 0, CfrTil_DObject_New, 0, 0, 0, "DObject", "Root" },
    //{ "object", 0, 0, CfrTil_DObject, 0, 0, 0, "DObject", "Root" },

    // this section can be implemented by lower level calls - internally
    { "word", 0, 0, CfrTil_Word, 0, 0, 0, "Reserved", "Compiler" },
    { ":", 0, 0, _CfrTil_Colon, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "semi", 0, 0, CfrTil_SemiColon, KEYWORD, 0, 0, "Reserved", "Compiler" },
    { ";", 0, 0, CfrTil_SemiColon, IMMEDIATE | KEYWORD, SYNTACTIC, 0, "Reserved", "Compiler" },
    { "}", 0, 0, CfrTil_EndBlock, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" }, // moved to init.cft and renamed below
    { "{", 0, 0, ( block ) CfrTil_BeginBlock, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" }, // moved to init.cft and renamed below
    { "end", 0, 0, CfrTil_EndBlock, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "immediate", 0, 0, CfrTil_Immediate, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "stackVariable", 0, 0, CfrTil_StackVariable, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "syntactic", 0, 0, CfrTil_Syntactic, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },

    //{ "_dlsymWord", 0, 0, CfrTil_DlsymWord, 0, 0, 0, "Reserved", "Compiler" },
    { "dlsym:", 0, 0, CfrTil_Dlsym, 0, 0, 0, "Reserved", "Compiler" },
    { "keyword", 0, 0, CfrTil_Keyword, IMMEDIATE, 0, 0, "Reserved", "Compiler" },
    { "swap", 0, 0, CfrTil_Swap, IMMEDIATE, 0, 0, "Reserved", "Compiler" },
    { "|}", 0, 0, CfrTil_RightBracket, IMMEDIATE, 0, 0, "Reserved", "Compiler" },
    { "{|", 0, 0, CfrTil_LeftBracket, IMMEDIATE, 0, 0, "Reserved", "Compiler" },

    { "c_syntaxOn", 0, 0, CfrTil_C_Syntax_On, IMMEDIATE, 0, 0, "Compiler", "Root" }, // put this here so Compiler will be in Root namespace and Compiler will close to the top
    { "c_syntaxOff", 0, 0, CfrTil_C_Syntax_Off, IMMEDIATE, 0, 0, "Compiler", "Root" },
    //{ "tail", 0, 0, CfrTil_Tail, IMMEDIATE | CATEGORY_TAIL | CATEGORY_UNMOVEABLE, 0, 0, "Compiler", "Root" },
    //{ "recurse", 0, 0, CfrTil_SetupRecursiveCall, IMMEDIATE | CATEGORY_RECURSIVE, 0, 0, "Compiler", "Root" }, // put this here so "Compiler" will be in "Root"
    { "goto", 0, 0, CfrTil_Goto, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "continue", 0, 0, CfrTil_Continue, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "return", 0, 0, CfrTil_Return, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "break", 0, 0, CfrTil_Break, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "noop", 0, 0, CfrTil_NoOp, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "macro", 0, 0, CfrTil_Word, IMMEDIATE, 0, 0, "Compiler", "Root" },
    //{ ":recursive", 0, 0, CfrTil_BeginRecursiveWord, 0, 0, 0, "Compiler", "Root" },
    //{ "recursive;", 0, 0, CfrTil_EndRecursiveWord, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_variable", 0, 0, CfrTil_Variable, 0, 0, 0, "Compiler", "Root" },
    { "variable", 0, 0, CfrTil_Variable, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_constant", 0, 0, CfrTil_Constant, 0, 0, 0, "Compiler", "Root" },
    { "constant", 0, 0, CfrTil_Constant, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "literal", 0, 0, CfrTil_Literal, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_literal", 0, 0, CfrTil_Literal, 0, 0, 0, "Compiler", "Root" },
    { "_end", 0, 0, CfrTil_EndBlock, 0, 0, 0, "Compiler", "Root" },
    { "begin", 0, 0, ( block ) CfrTil_BeginBlock, 0, 0, 0, "Compiler", "Root" },
    { "Here", 0, 0, CfrTil_Here, CATEGORY_OP_STACK, 0, 0, "Compiler", "Root" }, //anything that pushes it result onto the stack should be CATEGORY_OP !?
    { "code", 0, 0, CfrTil_Code, 0, 0, 0, "Compiler", "Root" },
    { "_immediate", 0, 0, CfrTil_Immediate, 0, 0, 0, "Compiler", "Root" },
    { "?immediate", 0, 0, CfrTil_IsImmediate, INFIXABLE, 0, 0, "Compiler", "Root" },
    { "inline", 0, 0, CfrTil_Inline, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_prefix", 0, 0, CfrTil_Prefix, 0, 0, 0, "Compiler", "Root" },
    { "prefix", 0, 0, CfrTil_Prefix, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "infixOn", 0, 0, CfrTil_InfixModeOn, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "infixOff", 0, 0, CfrTil_InfixModeOff, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "prefixOn", 0, 0, CfrTil_PrefixModeOn, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "prefixOff", 0, 0, CfrTil_PrefixModeOff, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "debugWord", 0, 0, CfrTil_DebugWord, 0, 0, 0, "Compiler", "Root" },
    { "@", 0, MOV, CfrTil_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" }, // fetch
    { "load", 0, MOV, CfrTil_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    { "@=", 0, 0, CfrTil_AtEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    //{ "at", 0, 0, CfrTil_Peek, CATEGORY_FETCH, 0, 0, "Compiler", "Root" },
    { "peek", 0, MOV, CfrTil_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    { "!", 0, MOV, CfrTil_Store, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_STORE, 0, 0, "Compiler", "Root" },
    { "=", 0, MOV, CfrTil_Poke, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL | INFIXABLE | KEYWORD, 0, 0, "Compiler", "Root" },
    { "poke", 0, MOV, CfrTil_Poke, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL, 0, 0, "Compiler", "Root" },
    { "store", 0, MOV, CfrTil_Store, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_STORE, 0, 0, "Compiler", "Root" },
    { "quote", 0, 0, CfrTil_SingleQuote, KEYWORD, 0, 0, "Compiler", "Root" },
    //{ "_tick", 0, 0, CfrTil_Tick, KEYWORD, 0, 0, "Compiler", "Root" },
    { "_tick", 0, 0, CfrTil_SingleQuote, KEYWORD, 0, 0, "Compiler", "Root" },
    //{ "\"", 0, 0, CfrTil_DoubleQuote, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "token", 0, 0, CfrTil_Token, STACK_VARIABLE, 0, 0, "Compiler", "Root" },
    { "getStringToEndOfLine", 0, 0, String_GetStringToEndOfLine, 0, 0, 0, "Compiler", "Root" },
    { "sourceCodeInit", 0, 0, CfrTil_SourceCode_Init, 0, 0, 0, "Compiler", "Root" },
    { "sourceCodeOn", 0, 0, CfrTil_Lexer_SourceCodeOn, 0, 0, 0, "Compiler", "Root" },
    { ")", 0, 0, CfrTil_NoOp, IMMEDIATE | KEYWORD, NO_OP_WORD|RIGHT_PAREN, 0, "Compiler", "Root" },

    { ",", 0, 0, CompileInt32, 0, 0, 0, "Compiling", "Compiler" },
    { "4,", 0, 0, CompileInt32, 0, 0, 0, "Compiling", "Compiler" },
    { "8,", 0, 0, CompileInt64, 0, 0, 0, "Compiling", "Compiler" },
    { "1,", 0, 0, CompileByte, 0, 0, 0, "Compiling", "Compiler" },
    { "compileByte", 0, 0, CompileByte, 0, 0, 0, "Compiling", "Compiler" },
    { "2,", 0, 0, CompileInt16, 0, 0, 0, "Compiling", "Compiler" },
    { "n,", 0, 0, CompileN, 0, 0, 0, "Compiling", "Compiler" },
    { "_compileCall", 0, 0, CompileCall, 0, 0, 0, "Compiling", "Compiler" },
    { "_compileWord", 0, 0, CompileACfrTilWord, 0, 0, 0, "Compiling", "Compiler" },
    { "_compileThisWord", 0, 0, Word_Compile_CurrentRunningWord, 0, 0, 0, "Compiling", "Compiler" },
    { "compileThisWord", 0, 0, Word_Compile_CurrentRunningWord, IMMEDIATE, 0, 0, "Compiling", "Compiler" },
    { "peekReg", 0, 0, CfrTil_PeekReg, 0, 0, 0, "Compiling", "Compiler" },
    { "pokeRegWithValue", 0, 0, CfrTil_PokeRegWithValue, 0, 0, 0, "Compiling", "Compiler" },
    { "pokeRegAtAddress", 0, 0, CfrTil_PokeRegAtAddress, 0, 0, 0, "Compiling", "Compiler" },
    //{ "rsp", 0, 0, CfrTil_Rsp, 0, 0, 0, "Compiling", "Compiler" },

    { 0 }
} ;

MachineCodePrimitive MachineCodePrimitives [] = {
    //{ "getRsp", CPRIMITIVE, 0, ( byte* ) Compile_Debug_GetRSP, -1, "System", "Root" },
    //{ "restoreCpuState", CPRIMITIVE, 0, ( byte* ) Compile_CpuState_Restore, 0, "System", "Root" },
    //{ "saveCpuState", CPRIMITIVE, 0, ( byte* ) Compile_CpuState_Save, 0, "System", "Root" },
    //{ "saveCpu2State", CPRIMITIVE, 0, ( byte* ) Compile_CpuState_Save, 0, "System", "Root" },
    //{ "restoreCpu2State", CPRIMITIVE, 0, ( byte* ) Compile_CpuState_Restore, 0, "System", "Root" },
    //{ "saveCpuState", CPRIMITIVE, 0, ( byte* ) Compile_CpuState_Save, 0, "Debug", "Root" },
    //{ "restoreCpuState", CPRIMITIVE, 0, ( byte* ) Compile_CpuState_Restore, 0, "Debug", "Root" },
    //{ "restoreSelectedCpuState", CPRIMITIVE, 0, ( byte* ) _Compile_CpuState_RestoreSelected, 0, "System", "Root" },
    //{ "saveSelectedCpuState", CPRIMITIVE, 0, ( byte* ) _Compile_CpuState_SaveSelected, 0, "System", "Root" },
    //{ "callCurrentBlock", CPRIMITIVE, 0, ( byte* ) Compile_Call_CurrentBlock, 0, "System", "Root" },
    //{ "callCfrTilWord", CPRIMITIVE, 0, ( byte* ) Compile_Call_CfrTilWord, 0, "System", "Root" },
    //{ "set_CfrTilRsp_FromReturnStackPointer", CPRIMITIVE, 0, ( byte* ) Compile_Set_CfrTilRspReg_FromReturnStackPointer, 0, "System", "Root" },
    //{ "set_ReturnStackPointer_FromCfrTilRsp", CPRIMITIVE, 0, ( byte* ) Compile_Set_ReturnStackPointer_FromCfrTilRspReg, 0, "System", "Root" },
    //{ "set_DspReg_FromDataStackPointer", CPRIMITIVE, 0, ( byte* ) Compile_Set_DspReg_FromDataStackPointer, 0, "System", "Root" },
    //{ "set_DataStackPointer_FromDspReg", CPRIMITIVE, 0, ( byte* ) Compile_Set_DataStackPointer_FromDspReg, 0, "System", "Root" },
    { "_cwLocation", CPRIMITIVE | INTERPRET_DBG, 0, 0, ( byte* ) _Compile_WordCompiledAt_Location, - 1, "Debug", "Root" },
    //{ "<dbg>", CPRIMITIVE | INTERPRET_DBG, RT_STEPPING_DEBUG, 0, ( byte* ) _Compile_DebugRuntimeBreakpoint, - 1, "Debug", "Root" },
    { "<dbg>", CPRIMITIVE, RT_STEPPING_DEBUG, 0, ( byte* ) _Compile_DebugRuntimeBreakpoint, - 1, "Debug", "Root" },
    { "rspReg", CPRIMITIVE, 0, 0, ( byte* ) _Compile_RspReg_Get, - 1, "System", "Root" },
    { "rspReg@", CPRIMITIVE, 0, 0, ( byte* ) _Compile_RspReg_Fetch, - 1, "System", "Root" },
    { ">rspReg", CPRIMITIVE, 0, 0, ( byte* ) _Compile_RspReg_To, - 1, "System", "Root" },
    { "rspReg>", CPRIMITIVE, 0, 0, ( byte* ) _Compile_RspReg_From, - 1, "System", "Root" },
    { "rspRegdrop", CPRIMITIVE, 0, 0, ( byte* ) _Compile_RspReg_Drop, - 1, "Debug", "Root" },
    { "rspReg!", CPRIMITIVE, 0, 0, ( byte* ) _Compile_RspReg_Store, - 1, "System", "Root" },
    //{ "popDspToR8AndCall", CPRIMITIVE, 0, ( byte* ) _Compile_PopDspToR8AndCall, - 1, "System", "Root" },
    { 0 }
} ;


